// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker.proto

package io.grpc.hellos;

public final class Tracker {
  private Tracker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface getCriticalPointRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gradlegRPC.getCriticalPointRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 robotID = 1;</code>
     * @return The robotID.
     */
    int getRobotID();

    /**
     * <code>int32 criticalPoint = 2;</code>
     * @return The criticalPoint.
     */
    int getCriticalPoint();
  }
  /**
   * Protobuf type {@code gradlegRPC.getCriticalPointRequestMessage}
   */
  public static final class getCriticalPointRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gradlegRPC.getCriticalPointRequestMessage)
      getCriticalPointRequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getCriticalPointRequestMessage.newBuilder() to construct.
    private getCriticalPointRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getCriticalPointRequestMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new getCriticalPointRequestMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getCriticalPointRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              robotID_ = input.readInt32();
              break;
            }
            case 16: {

              criticalPoint_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointRequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.hellos.Tracker.getCriticalPointRequestMessage.class, io.grpc.hellos.Tracker.getCriticalPointRequestMessage.Builder.class);
    }

    public static final int ROBOTID_FIELD_NUMBER = 1;
    private int robotID_;
    /**
     * <code>int32 robotID = 1;</code>
     * @return The robotID.
     */
    @java.lang.Override
    public int getRobotID() {
      return robotID_;
    }

    public static final int CRITICALPOINT_FIELD_NUMBER = 2;
    private int criticalPoint_;
    /**
     * <code>int32 criticalPoint = 2;</code>
     * @return The criticalPoint.
     */
    @java.lang.Override
    public int getCriticalPoint() {
      return criticalPoint_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (robotID_ != 0) {
        output.writeInt32(1, robotID_);
      }
      if (criticalPoint_ != 0) {
        output.writeInt32(2, criticalPoint_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (robotID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, robotID_);
      }
      if (criticalPoint_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, criticalPoint_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.hellos.Tracker.getCriticalPointRequestMessage)) {
        return super.equals(obj);
      }
      io.grpc.hellos.Tracker.getCriticalPointRequestMessage other = (io.grpc.hellos.Tracker.getCriticalPointRequestMessage) obj;

      if (getRobotID()
          != other.getRobotID()) return false;
      if (getCriticalPoint()
          != other.getCriticalPoint()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROBOTID_FIELD_NUMBER;
      hash = (53 * hash) + getRobotID();
      hash = (37 * hash) + CRITICALPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getCriticalPoint();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.hellos.Tracker.getCriticalPointRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gradlegRPC.getCriticalPointRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gradlegRPC.getCriticalPointRequestMessage)
        io.grpc.hellos.Tracker.getCriticalPointRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointRequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.hellos.Tracker.getCriticalPointRequestMessage.class, io.grpc.hellos.Tracker.getCriticalPointRequestMessage.Builder.class);
      }

      // Construct using io.grpc.hellos.Tracker.getCriticalPointRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        robotID_ = 0;

        criticalPoint_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointRequestMessage_descriptor;
      }

      @java.lang.Override
      public io.grpc.hellos.Tracker.getCriticalPointRequestMessage getDefaultInstanceForType() {
        return io.grpc.hellos.Tracker.getCriticalPointRequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.hellos.Tracker.getCriticalPointRequestMessage build() {
        io.grpc.hellos.Tracker.getCriticalPointRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.hellos.Tracker.getCriticalPointRequestMessage buildPartial() {
        io.grpc.hellos.Tracker.getCriticalPointRequestMessage result = new io.grpc.hellos.Tracker.getCriticalPointRequestMessage(this);
        result.robotID_ = robotID_;
        result.criticalPoint_ = criticalPoint_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.hellos.Tracker.getCriticalPointRequestMessage) {
          return mergeFrom((io.grpc.hellos.Tracker.getCriticalPointRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.hellos.Tracker.getCriticalPointRequestMessage other) {
        if (other == io.grpc.hellos.Tracker.getCriticalPointRequestMessage.getDefaultInstance()) return this;
        if (other.getRobotID() != 0) {
          setRobotID(other.getRobotID());
        }
        if (other.getCriticalPoint() != 0) {
          setCriticalPoint(other.getCriticalPoint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.hellos.Tracker.getCriticalPointRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.hellos.Tracker.getCriticalPointRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int robotID_ ;
      /**
       * <code>int32 robotID = 1;</code>
       * @return The robotID.
       */
      @java.lang.Override
      public int getRobotID() {
        return robotID_;
      }
      /**
       * <code>int32 robotID = 1;</code>
       * @param value The robotID to set.
       * @return This builder for chaining.
       */
      public Builder setRobotID(int value) {
        
        robotID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 robotID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRobotID() {
        
        robotID_ = 0;
        onChanged();
        return this;
      }

      private int criticalPoint_ ;
      /**
       * <code>int32 criticalPoint = 2;</code>
       * @return The criticalPoint.
       */
      @java.lang.Override
      public int getCriticalPoint() {
        return criticalPoint_;
      }
      /**
       * <code>int32 criticalPoint = 2;</code>
       * @param value The criticalPoint to set.
       * @return This builder for chaining.
       */
      public Builder setCriticalPoint(int value) {
        
        criticalPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 criticalPoint = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCriticalPoint() {
        
        criticalPoint_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gradlegRPC.getCriticalPointRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:gradlegRPC.getCriticalPointRequestMessage)
    private static final io.grpc.hellos.Tracker.getCriticalPointRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.hellos.Tracker.getCriticalPointRequestMessage();
    }

    public static io.grpc.hellos.Tracker.getCriticalPointRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getCriticalPointRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<getCriticalPointRequestMessage>() {
      @java.lang.Override
      public getCriticalPointRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getCriticalPointRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getCriticalPointRequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getCriticalPointRequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.hellos.Tracker.getCriticalPointRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface getCriticalPointResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gradlegRPC.getCriticalPointResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 criticalPoint = 1;</code>
     * @return The criticalPoint.
     */
    int getCriticalPoint();
  }
  /**
   * Protobuf type {@code gradlegRPC.getCriticalPointResponseMessage}
   */
  public static final class getCriticalPointResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gradlegRPC.getCriticalPointResponseMessage)
      getCriticalPointResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use getCriticalPointResponseMessage.newBuilder() to construct.
    private getCriticalPointResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private getCriticalPointResponseMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new getCriticalPointResponseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private getCriticalPointResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              criticalPoint_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.hellos.Tracker.getCriticalPointResponseMessage.class, io.grpc.hellos.Tracker.getCriticalPointResponseMessage.Builder.class);
    }

    public static final int CRITICALPOINT_FIELD_NUMBER = 1;
    private int criticalPoint_;
    /**
     * <code>int32 criticalPoint = 1;</code>
     * @return The criticalPoint.
     */
    @java.lang.Override
    public int getCriticalPoint() {
      return criticalPoint_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (criticalPoint_ != 0) {
        output.writeInt32(1, criticalPoint_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (criticalPoint_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, criticalPoint_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.hellos.Tracker.getCriticalPointResponseMessage)) {
        return super.equals(obj);
      }
      io.grpc.hellos.Tracker.getCriticalPointResponseMessage other = (io.grpc.hellos.Tracker.getCriticalPointResponseMessage) obj;

      if (getCriticalPoint()
          != other.getCriticalPoint()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CRITICALPOINT_FIELD_NUMBER;
      hash = (53 * hash) + getCriticalPoint();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.hellos.Tracker.getCriticalPointResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gradlegRPC.getCriticalPointResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gradlegRPC.getCriticalPointResponseMessage)
        io.grpc.hellos.Tracker.getCriticalPointResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.hellos.Tracker.getCriticalPointResponseMessage.class, io.grpc.hellos.Tracker.getCriticalPointResponseMessage.Builder.class);
      }

      // Construct using io.grpc.hellos.Tracker.getCriticalPointResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        criticalPoint_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.hellos.Tracker.internal_static_gradlegRPC_getCriticalPointResponseMessage_descriptor;
      }

      @java.lang.Override
      public io.grpc.hellos.Tracker.getCriticalPointResponseMessage getDefaultInstanceForType() {
        return io.grpc.hellos.Tracker.getCriticalPointResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.hellos.Tracker.getCriticalPointResponseMessage build() {
        io.grpc.hellos.Tracker.getCriticalPointResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.hellos.Tracker.getCriticalPointResponseMessage buildPartial() {
        io.grpc.hellos.Tracker.getCriticalPointResponseMessage result = new io.grpc.hellos.Tracker.getCriticalPointResponseMessage(this);
        result.criticalPoint_ = criticalPoint_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.hellos.Tracker.getCriticalPointResponseMessage) {
          return mergeFrom((io.grpc.hellos.Tracker.getCriticalPointResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.hellos.Tracker.getCriticalPointResponseMessage other) {
        if (other == io.grpc.hellos.Tracker.getCriticalPointResponseMessage.getDefaultInstance()) return this;
        if (other.getCriticalPoint() != 0) {
          setCriticalPoint(other.getCriticalPoint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.hellos.Tracker.getCriticalPointResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.hellos.Tracker.getCriticalPointResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int criticalPoint_ ;
      /**
       * <code>int32 criticalPoint = 1;</code>
       * @return The criticalPoint.
       */
      @java.lang.Override
      public int getCriticalPoint() {
        return criticalPoint_;
      }
      /**
       * <code>int32 criticalPoint = 1;</code>
       * @param value The criticalPoint to set.
       * @return This builder for chaining.
       */
      public Builder setCriticalPoint(int value) {
        
        criticalPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 criticalPoint = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCriticalPoint() {
        
        criticalPoint_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gradlegRPC.getCriticalPointResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:gradlegRPC.getCriticalPointResponseMessage)
    private static final io.grpc.hellos.Tracker.getCriticalPointResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.hellos.Tracker.getCriticalPointResponseMessage();
    }

    public static io.grpc.hellos.Tracker.getCriticalPointResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<getCriticalPointResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<getCriticalPointResponseMessage>() {
      @java.lang.Override
      public getCriticalPointResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getCriticalPointResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<getCriticalPointResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<getCriticalPointResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.hellos.Tracker.getCriticalPointResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradlegRPC_getCriticalPointRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradlegRPC_getCriticalPointRequestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradlegRPC_getCriticalPointResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradlegRPC_getCriticalPointResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtracker.proto\022\ngradlegRPC\"H\n\036getCritic" +
      "alPointRequestMessage\022\017\n\007robotID\030\001 \001(\005\022\025" +
      "\n\rcriticalPoint\030\002 \001(\005\"8\n\037getCriticalPoin" +
      "tResponseMessage\022\025\n\rcriticalPoint\030\001 \001(\0052" +
      "{\n\016TrackerService\022i\n\016gCriticalPoint\022*.gr" +
      "adlegRPC.getCriticalPointRequestMessage\032" +
      "+.gradlegRPC.getCriticalPointResponseMes" +
      "sageB\020\n\016io.grpc.hellosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gradlegRPC_getCriticalPointRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gradlegRPC_getCriticalPointRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradlegRPC_getCriticalPointRequestMessage_descriptor,
        new java.lang.String[] { "RobotID", "CriticalPoint", });
    internal_static_gradlegRPC_getCriticalPointResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gradlegRPC_getCriticalPointResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradlegRPC_getCriticalPointResponseMessage_descriptor,
        new java.lang.String[] { "CriticalPoint", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
